### ISSUE TITLE
Linux please

### ISSUE THREAD

**Issue by codydbgt** [Pelipoika/PathFollower#1]
nice work but 99% of all hosts run on linux :P why put all this work in and have 1% use it like 3 people ... if that

**Comment by Pelipoika** [comment]
It is not possible to make this work for Linux, it did work in the past on Linux but why it does not now is explained in the readme

**Comment by codydbgt** [comment]
sir i envy your waste of time shame i cant use it

**Comment by Pelipoika** [comment]
You're a waste of time

**Comment by codydbgt** [comment]
ya i am :) i want to die
